---
language: python
python: "2.7"
php:
  - '5.6'

sudo: enabled
dist: trusty

before_install:
  # Update APT caches.
  - sudo apt-get update
  # Install some system dependencies.
  - sudo apt-get install build-essential dkms unzip linux-headers-4.4.0-51-generic
  # Install VirtualBox.
  - wget http://download.virtualbox.org/virtualbox/5.1.14/virtualbox-5.1_5.1.14-112924~Ubuntu~trusty_amd64.deb
  - sudo dpkg -i virtualbox-5.1_5.1.14-112924~Ubuntu~trusty_amd64.deb
  # Install Ansible.
  - pip install ansible
  - ansible --version
  # Install Vagrant.
  - wget https://releases.hashicorp.com/vagrant/1.9.1/vagrant_1.9.1_x86_64.deb
  - sudo dpkg -i vagrant_1.9.1_x86_64.deb
  - vagrant -v
  # Install vagrant plugins.
  - vagrant plugin install vagrant-hostsupdater
  - vagrant plugin install vagrant-auto_network
  - vagrant plugin list
  - vagrant box add --name geerlingguy/ubuntu1604 https://app.vagrantup.com/geerlingguy/boxes/ubuntu1604

install:
  # Clear composer caches.
  - composer global clearcache
  # Update composer.
  - composer global self-update
  # Install this package.
  - composer global require valentine94/vmgen-php:dev-master
  # Install Coder.
  - composer global require "drupal/coder:8.2.12"
  # Set up standards.
  - composer global require dealerdirect/phpcodesniffer-composer-installer
  - export PATH="$PATH:$HOME/.composer/vendor/bin"
  - pear channel-update pear.php.net
  - pear install pear/PHP_CodeSniffer
  - phpenv rehash
  - phpcs -i
script:
  # Run VM generator.
  - /home/travis/.config/composer/vendor/valentine94/vmgen-php/vmgen-php --php=7 --project-name=test
  # Check if directory vm has been created.
  - ls -l /home/travis/projects/test
  # Check if all files under vm directory exists.
  - ls -l /home/travis/projects/test/vm
  # Check if config.yml has been created and it's not empty.
  - test -s /home/travis/projects/test/vm/config.yml; echo $?
