---
language: python
python: "2.7"
php:
  - '5.6'

sudo: enabled
dist: trusty

before_install:
  # Update APT caches.
  - sudo apt-get update
  # Install some system dependencies.
  - sudo apt-get install build-essential dkms unzip linux-headers-4.4.0-51-generic

install:
  # Clear composer caches.
  - composer global clearcache
  # Update composer.
  - composer global self-update
  # Install this package.
  - composer global require valentine94/vmgen-php:dev-master
  # Install Coder.
  - composer global require "drupal/coder:8.2.12"
  # Set up standards.
  - composer global require dealerdirect/phpcodesniffer-composer-installer
  - export PATH="$PATH:$HOME/.composer/vendor/bin"
  - pear channel-update pear.php.net
  - pear install pear/PHP_CodeSniffer
  - phpenv rehash
  - phpcs -i
script:
  # Run VM generator.
  - /home/travis/.config/composer/vendor/valentine94/vmgen-php/vmgen-php --php=7 --project-name=test
  # Check if directory vm has been created.
  - ls -l /home/travis/projects/test
  # Check if all files under vm directory exists.
  - ls -l /home/travis/projects/test/vm
  # Check if config.yml has been created and it's not empty.
  - test -s /home/travis/projects/test/vm/config.yml; echo $?
