---
language: python
python: "2.7"
php:
  - '7.0'

sudo: enabled
dist: trusty

install:
  # Clear composer caches.
  - composer global clearcache
  # Update composer.
  - composer global self-update
  # Install this package.
  - composer global require valentine94/vmgen-php
script:
  # Run VM generator.
  - /home/travis/.config/composer/vendor/valentine94/vmgen-php/vmgen-php --php=7 --project-name=test
  # Check if directory vm has been created.
  - ls -l ~/projects/test
  # Check if all files under vm directory exists.
  - ls -l ~/projects/test/vm
