---
language: python
python: "2.7"
php:
  - '5.5'
  - '5.6'
  - '7.0'
  - '7.1'

sudo: enabled
dist: trusty

before_install:
  # Workaround for correctly working PHPCS.
  - pear config-set php_dir $(php -r 'echo substr(get_include_path(),2);')
  - if [[ ${TRAVIS_PHP_VERSION:0:1} == "5" || ${TRAVIS_PHP_VERSION:0:1} == "7" ]]; then echo "include_path='.:/home/travis/.phpenv/versions/$(phpenv version-name)/lib/php/pear'" >> ~/.phpenv/versions/$(phpenv version-name)/etc/php.ini; fi
  # Clear composer caches.
  - composer global clearcache
  # Update composer.
  - composer global self-update

install:
  # Install this package.
  - composer global require valentine94/vmgen-php:dev-master
  # Install Coder.
  - composer global require "drupal/coder:8.2.12"
  # Install PHP_CodeSniffer.
  - pear channel-update pear.php.net
  - pear install pear/PHP_CodeSniffer-2.9.1
  - phpenv rehash
  # Register Drupal coding standards.
  - phpcs --config-set installed_paths /home/travis/.config/composer/vendor/drupal/coder/coder_sniffer
script:
  # Check coding standards.
  - phpcs --standard=Drupal --extensions=php,inc --ignore=*.md /home/travis/.config/composer/vendor/valentine94
  - phpcs --standard=DrupalPractice --extensions=php,inc --ignore=*.md /home/travis/.config/composer/vendor/valentine94
  # Run VM generator.
  - /home/travis/.config/composer/vendor/valentine94/vmgen-php/vmgen-php --php=7 --project-name=test
  # Check if directory vm has been created.
  - ls -l /home/travis/projects/test
  # Check if all files under vm directory exists.
  - ls -l /home/travis/projects/test/vm
  # Check if config.yml has been created and it's not empty.
  - test -s /home/travis/projects/test/vm/config.yml; echo $?
