---
language: python
python: "2.7"
php:
  - '7.0'

sudo: required
dist: trusty

install:
  # Clear composer caches.
  - composer global clearcache
  # Install this package.
  - composer global require valentine94/vmgen-php
  # Check availability of the 'vmgen-php' command.
  - which vmgen-php
script:
  # Run VM generator.
  - vmgen-php --php=7 --project-name=test
  # Check if directory vm has been created.
  - ls -l ~/projects/test
  # Check if all files under vm directory exists.
  - ls -l ~/projects/test/vm
